import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import React from 'react';
import styles from './styles.module.css';
import './globals.css';

const geistSans = Geist({
  variable: "--font-geist-sanss",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <head>
        <title>Map Page</title>
      </head>
      <body className={styles.body}>
        {children}
      </body>
    </html>
  )
}
