version: "3.8"
services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      #- ./docker/mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"

  backend:
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile
    container_name: hono_backend
    restart: always
    environment:
      - NODE_ENV=development
        DATABASE_URL:"mysql://root:rootpassword@localhost:3306/mydb"
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    command: ["./docker/wait-for-it.sh", "mysql:3306", "--", "bun", "run", "dev"]
    tty: true
    stdin_open: true